name: dss
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.10.8=py38h578d9bd_1
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - intel-openmp=2022.0.1=h06a4308_3633
  - jpeg=9d=h7f8727e_0
  - lame=3.100=h7f98852_1001
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libblas=3.9.0=13_linux64_mkl
  - libcblas=3.9.0=13_linux64_mkl
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=13_linux64_mkl
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.0.10=hc3755c2_1005
  - libuv=1.40.0=h7b6447c_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2022.0.1=h06a4308_117
  - ncurses=6.3=h7f8727e_2
  - nettle=3.6=he412f7d_0
  - ninja=1.10.2=h4bd325d_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1m=h7f8727e_0
  - pip=21.2.4=py38h06a4308_0
  - python=3.8.12=h12debd9_0
  - python_abi=3.8=2_cp38
  - pytorch=1.10.2=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h7f8727e_1
  - sqlite=3.37.2=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - torchaudio=0.10.2=py38_cu113
  - torchvision=0.11.3=py38_cu113
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - antlr4-python3-runtime==4.8
    - argcomplete==2.0.0
    - async-timeout==4.0.2
    - attrs==21.4.0
    - axel==0.0.7
    - boto==2.49.0
    - cachetools==5.0.0
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - click==8.0.3
    - cmake==3.22.2
    - colorama==0.4.4
    - commonmark==0.9.1
    - crcmod==1.7
    - cryptography==36.0.1
    - cycler==0.11.0
    - datasets==1.18.3
    - deprecated==1.2.13
    - dill==0.3.4
    - docker-pycreds==0.4.0
    - einops==0.4.0
    - fasteners==0.17.3
    - filelock==3.6.0
    - fonttools==4.29.1
    - frozenlist==1.3.0
    - fsspec==2022.1.0
    - future==0.18.2
    - gcs-oauth2-boto-plugin==3.0
    - gitdb==4.0.9
    - gitpython==3.1.26
    - google-apitools==0.5.32
    - google-auth==2.6.0
    - google-auth-oauthlib==0.4.6
    - google-reauth==0.1.1
    - grpcio==1.43.0
    - gsutil==5.6
    - httplib2==0.20.4
    - huggingface-hub==0.4.0
    - hydra-core==1.1.1
    - idna==3.3
    - importlib-metadata==4.11.1
    - importlib-resources==5.4.0
    - joblib==1.1.0
    - kiwisolver==1.3.2
    - llvmlite==0.38.0
    - markdown==3.3.6
    - matplotlib==3.5.1
    - monotonic==1.6
    - multidict==6.0.2
    - multiprocess==0.70.12.2
    - munch==2.5.0
    - numba==0.55.1
    - numpy==1.21.5
    - oauth2client==4.1.3
    - oauthlib==3.2.0
    - omegaconf==2.1.1
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.4.1
    - pathtools==0.1.2
    - patsy==0.5.2
    - pillow==9.0.1
    - promise==2.3
    - protobuf==3.19.4
    - psutil==5.9.0
    - pyarrow==7.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pydeprecate==0.3.1
    - pygments==2.11.2
    - pykeops==1.5
    - pyopenssl==22.0.0
    - pyparsing==3.0.7
    - python-dateutil==2.8.2
    - pytorch-lightning==1.5.10
    - pytz==2021.3
    - pyu2f==0.1.5
    - pyyaml==6.0
    - regex==2022.1.18
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - retry-decorator==1.1.1
    - rich==11.2.0
    - rsa==4.7.2
    - sacremoses==0.0.47
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - sentry-sdk==1.5.5
    - setuptools==59.5.0
    - shortuuid==1.0.8
    - six==1.16.0
    - sklearn==0.0
    - sktime==0.10.0
    - smmap==5.0.0
    - statsmodels==0.13.2
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==1.1.0
    - threadpoolctl==3.1.0
    - tokenizers==0.11.5
    - torchmetrics==0.7.2
    - torchtext==0.11.2
    - tqdm==4.62.3
    - transformers==4.16.2
    - urllib3==1.26.8
    - wandb==0.12.10
    - werkzeug==2.0.3
    - wrapt==1.13.3
    - xxhash==2.0.2
    - yarl==1.7.2
    - yaspin==2.1.0
    - zipp==3.7.0

